name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, xdebug
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

  grumphp:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run GrumPHP
        run: vendor/bin/grumphp run --no-interaction --ansi

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHPUnit with coverage
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ matrix.php-version }}
          path: build/logs/clover.xml

  deploy-coverage:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download coverage artifacts
        uses: actions/download-artifact@v3
        with:
          path: build/logs

      - name: Generate Coverage Badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          clover-file: build/logs/clover.xml
          output-path: coverage-badge.svg
          commit-message: 'Update coverage badge'
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/logs
          publish_branch: gh-pages
