name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: curl, xdebug
          coverage: xdebug
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest


      - name: Upload dependencies artifact
        uses: actions/upload-artifact@v3
        with:
          name: composer-vendor
          path: vendor/


  grumphp:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies artifact
        uses: actions/download-artifact@v3
        with:
          name: composer-vendor
          path: vendor/

      - name: Run GrumPHP
        run: vendor/bin/grumphp run --no-interaction --ansi

  test:
    needs: grumphp
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies artifact
        uses: actions/download-artifact@v3
        with:
          name: composer-vendor
          path: vendor/

      - name: Run PHPUnit with coverage
        run: |
          mkdir -p public/coverage-html build/logs
          vendor/bin/phpunit --coverage-html=public/coverage-html --coverage-clover=build/logs/clover.xml

      - name: Upload HTML coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage-${{ matrix.php-version }}
          path: public/coverage-html

      - name: Upload Clover coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: clover-coverage-${{ matrix.php-version }}
          path: build/logs/clover.xml

  deploy-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download HTML coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: html-coverage-8.4
          path: public/coverage-html

      - name: Generate Coverage Badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          clover-file: build/logs/clover.xml
          output-path: coverage-badge.svg
          commit-message: 'Ardian poc test Update coverage badge'
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/coverage-html
          publish_branch: gh-pages
